Support matching suggestions on spacebar
stocktwits/draft-js-plugins pull request #1
Opened 2019-09-12 12:27 UTC by ndrjkvc

## Use-case/Problem

https://github.com/draft-js-plugins/draft-js-plugins/issues/1048

## Implementation

Pass a matching function(with suggestions and lastSearchValue as arguments) from config as a prop to MentionSuggestions component. Use this function after spacebar is pressed to find a matching solution if there is one.

2019-09-13 07:32 UTC, szist approved these changes
can't you just point npm to a subfolder of a github repo? 
like:
github:stocktwits/draft-js-plugins/draft-js-mention-plugin ?

I would prefer not installing the whole repo as a runtime dependency everywhere :(

2019-09-13 07:44 UTC, szist commented
nevermind, you can't: https://github.com/npm/npm/issues/2974
Although there is a mention of gitpkg in a similar issue for yarn: https://github.com/yarnpkg/yarn/issues/4725 see commit https://github.com/yarnpkg/yarn/issues/4725#issuecomment-496683978 Might be good to investigate, but we might need yet-another repo from @afahy if we want to push the built package into it's own lib :)

2019-09-13 07:45 UTC, szist commented
fun fact, that issue for npm is 7 years old, so I don't think anything will change soon.

2019-09-13 07:47 UTC, szist commented
@ndrjkvc Anyhow, if we just want to move on, you would have to install the whole draft-js-plugins and if you want to use your built library should be able to just include:
`import createMentionPlugin from "draft-js-plugins/draft-js-mention-plugin"`

2019-09-13 07:59 UTC, ndrjkvc commented
> @ndrjkvc Anyhow, if we just want to move on, you would have to install the whole draft-js-plugins and if you want to use your built library should be able to just include:
> `import createMentionPlugin from "draft-js-plugins/draft-js-mention-plugin"`

That does not work, the plugins subfolders are empty after draft-js-plugins install (not really empty, they contain changelog, license, and readme)

2019-09-13 08:00 UTC, ndrjkvc commented
But there may be something we can write into package.json to let npm know it should download that folder fully. @szist

2019-09-13 08:31 UTC, szist commented
> But there may be something we can write into package.json to let npm know it should download that folder fully. @szist
you should add/create a .npmignore file, so that it doesn't use the .gitignore to remove all deps. See https://github.com/stocktwits/web-shared/blob/develop/.npmignore vs https://github.com/stocktwits/web-shared/blob/develop/.gitignore

2019-09-16 09:12 UTC, szist requested changes
do we still need the lib/*.js in git and the `files` in package.json ?

2019-09-16 10:37 UTC, ndrjkvc commented
> do we still need the lib/*.js in git and the `files` in package.json ?

No

2019-09-16 12:35 UTC, szist approved these changes

2019-09-19 08:47 UTC, merged